#!/bin/sh
# Takes screenshot, optimizes it with `optipng` and copies 
# its location to the clipboard.

#### Configuration
# Set the location to save your screenshots
SCREENSHOT_DIR="$HOME/Pictures/screenshots"

# Customize the output filenames, if necessary.
# Defaults to ISO 8601 - hostname.png
file="$(date -Iseconds)-$(hostname).png"
####

# Check prerequisites
for i in optipng xclip; do
    if [ ! "$(command -v $i)" ]; then
        echo "Warning: $i not found in PATH" >&2
    fi
done
for i in sh shotgun; do
    if [ ! "$(command -v $i)" ]; then
        echo "Error: prerequisite $i not found in PATH" >&2
        abort=true
    fi
done
[ "$abort" = "true" ] && exit 1


mkdir -p "$SCREENSHOT_DIR"
cd "$SCREENSHOT_DIR"

set -xe

shotgun "$file"
[ "$(command -v optipng)" ] && optipng "$file"

if [ "$(command -v xclip)" ]; then 
    printf '%s' "$SCREENSHOT_DIR/$file" | xclip -selection clipboard
else
    printf '%s' "$SCREENSHOT_DIR/$file"
fi
