#!/bin/sh

# Depends: sh, mktemp, curl, psutils, file
# Optional: torsocks (for handling onion links),
#   i3-sensible-terminal (for spawning a new terminal)

usage() {
    cat <<EOL
Usage:
 xdg-open [ -h | <PATH> | <URL> ]

A wrapper for /usr/bin/xdg-open that directly
passes media to their respective media players.

Options:
 -h, --help     Display this help message and exit
EOL
    exit 0
}
set -e

# Your preferred application with arguments
MEDIA_PLAYER="mpv"
IMAGE_VIEWER="feh -."

path=$(echo $PATH | sed "s|$HOME/bin:||g")
export PATH=$path

# Open an audio with content-type audio/*
open_audio () {
    $i3_sensible_terminal $MEDIA_PLAYER "$1"
}

# Open an url with content-type image/*
open_image () {
    setsid $IMAGE_VIEWER "$1" 2>&1 >/dev/null &
}

# Open an url with content-type video/*
open_video () {
    if [ "$2" = "true" ]; then
        case "$MEDIA_PLAYER" in mpv*) MEDIA_PLAYER="$MEDIA_PLAYER --loop-file=inf" ;; esac
    fi
    setsid $MEDIA_PLAYER "$1" 2>&1 >/dev/null &
}

# Open an url with content-types text/html and others
open_other () {
    case "$1" in
        http?://invidio.us/watch*|http?://*hooktube.com/watch*|http?://*youtube.com/watch*|http?://*youtu.be/*|rtmp://*)
            open_video "$1"
            ;;
        http?://*twitter.com/*)
            setsid xdg-open "$(echo "$1" | sed -E 's/(mobile.)*twitter.com/nitter.snopyta.org/')" &
            ;;
        http://*|https://*|gopher://*)
            # Not interested in onion links right now.
            # Reimplementing it ad a later poing
            #case "$1" in *.onion*) torsocks=torsocks ;; esac
            #tmp="$(mktemp)"
            #$torsocks curl -L "$1" > "$tmp"
            #open_file "$tmp" "$1"
            #rm "$tmp"
            setsid xdg-open "$1"
            ;;
        /*)
            open_file "$1" "file://$1"
            ;;
        *)
            open_file "$(pwd)/$1" "file://$(pwd)/$1"
    esac
}

open() {
    # Check what kind of link is being supplied
    content_type=$(curl -I "$1" \
        | grep -i '^content-type:' \
        | sed -E 's/^content-type: ([^;]+).*$/\1/gi')

    case "$content_type" in
        (video*)
            open_video "$1"
            ;;
        (image*)
            open_image "$1"
            ;;
        (audio*)
            open_audio "$1"
            ;;
        (*)
            open_other "$1"
            ;;
    esac
}

open_file() {
    content_type="$(file -b "$1")"

    case "$content_type" in
        JPEG*|PNG*)
            open_image "$1"
            ;;
        *MP4*|WebM*|GIF*)
            open_video "$1"
            ;;
        *audio*|*Audio*)
            open_audio "$1"
            ;;
        *)
            case "$2" in
                *.onion*)
                    setsid $i3_sensible_terminal torsocks w3m "$2" &
                    ;;
                *)
                    setsid xdg-open "$2" &
                    ;;
            esac
    esac
}


# Check prerequisites
for i in sh xdg-open mktemp curl \
        torsocks i3-sensible-terminal setsid sed; do
    if [ ! "$(command -v $i)" ]; then
        echo "Warning: prerequisite $i not found in PATH" >&2
    fi
done


# Spawn a new terminal if not invoked from a terminal
[ "$(readlink -f /proc/"$(ps -o ppid:1= -p $$)"/exe)" != "$(readlink -f "$SHELL")" ] && \
    i3_sensible_terminal="i3-sensible-terminal -e"


[ -z "$1" ] && usage
case "$1" in
    -h|--help)
        usage
        ;;
    *)
        open "$1"
        ;;
esac
